### ISSUE TITLE
Apigee Environment multi-tenancy

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-envoy#138]
- `Check` service will extract Apigee Environment information from request metadata, if available, and embed it into the auth context. Corresponding change is needed from the -golib.

- `env` in config.yaml will be made optional.

  - If `env` is provided:
    Requests regarding other Apigee envs will be rejected upfront. Or it works like before if no Apigee env is indicated in the request.

  - If `env` is absent:
    Multi-env support will be enabled. Requests will have to contain Apigee env info or be rejected.

**Comment by rockspore** [comment]
Regarding the first point, we need to decide what metadata we should check when the request is sent by Envoy.

**Comment by rockspore** [comment]
Integration tests will be needed once this is done.

**Comment by theganyo** [comment]
I'm going to add an explicit boolean flag in the config to set EA to multitenant - instead of implicitly assuming it based on lack of an env value. That way, we can still emit an error if the config is not set for multitenant and there's no env specified or conversely, the config is set for multitenant and there is an env specified. 

(BTW: I considered allowing a "default" env in a multitenant config, but I think this would be more likely to cause errors and confusion than offer any benefit to the user. Let me know if you think otherwise. cc: @srinandan )

**Comment by theganyo** [comment]
An alternative to the boolean flag could be to simply use a well-known special value like "*" for a multitenant environment. This would have the benefit of not having to change the config structure or CLI commands...

**Comment by theganyo** [comment]
Upon reflection, I'm going with the "*" for now. It's a simpler indicator, just as effective, and is less work. :)
