### ISSUE TITLE
use metadata instead of headers for authz -> ALS

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#146]
Currently, Apigee auth metadata is communicated to the access log service [via headers](https://github.com/apigee/apigee-remote-service-envoy/blob/master/server/header_context.go#L26). This was the only mechanism to do so in the Envoy v2 API. However, unless these headers are then stripped by properly configuring another Envoy filter, they will be sent on to the target service.

Envoy has added the ability to send this information using dynamic metadata in the [v3 API](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#service-auth-v3-checkresponse). Envoy Adapter should use this mechanism instead of headers. 

Requirements
- Switch to dynamic metadata instead of headers in the ext_authz response
- Only set headers if append metadata headers is set
- Use dynamic metadata instead of headers for RBAC
- Use dynamic metadata for analytics

**Comment by rockspore** [comment]
Question regarding the second requirement: is this "append metadata headers" a flag for the adapter?

**Comment by theganyo** [comment]
Oops. Scratch that requirement. We'll just use the filter.

**Comment by rockspore** [comment]
Because this dynamic metadata feature was only introduced in Envoy 1.16.0, to maintain the support of Envoy 1.15.x and Istio verions that use it, we will add a new config option `metadata_only`:
  * when set to false (default option), the adapter will append to request headers as well as send the metadata.
  * when set to true, the adapter will emit metadata only.

Accordingly, the StreamAccessLog service will fall back to use request headers if metadata is not found provided `metadata_only` being false.

**Comment by theganyo** [comment]
Hmm. I think it might be clearer to have a `append_headers` option that would be required for Envoy < 1.16.

**Comment by theganyo** [comment]
We can default this to true in any newly generated config. For existing customers, we can provide a release note.
