### ISSUE TITLE
disconnected quota fails refresh

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#31]
When the remote service is disconnected from Apigee, it's possible for a quota bucket to get stuck. There are two symptoms:

1. The local quota bucket attempts to refresh each second instead of using the backoff algorithm.
2. The local quota bucket fails to expire and reset its cached value at the end of the window.

(Once connected again, it syncs and operates correctly.)

**Comment by rockspore** [comment]
Update:
1. The first issue was due to the bucket sync() function not properly returning an error on failure in getting request from `/quota`.
2. The second issue persists (not always and a pattern is yet to be accurately determined) after the fix of the first one. More troubleshooting and tests are in progress.

**Comment by rockspore** [comment]
It looks like the expiryTime returned or decoded from the proxy is incorrect: 
```
quota/bucket.go:217	checking the quota bucket expirytime 2020-08-03 16:56:13.462869105 +0000 UTC m=+316.415213074 52560-03-26 11:20:00 +0000 UTC
```
where the first time is the current time and the second is the expiryTime.

**Comment by rockspore** [comment]
The flow variable `ratelimit.DistributedQuota.expiry.time` (as well as `system.timestamp` but not relevant here) is in milliseconds. It has been decoded as seconds and generated incorrect expiry time.
